(ns kcx.templates
  "Agent templates and behavioral constraints for KC-X"
  (:require
    [clojure.pprint :as pprint]
    [clojure.string :as str]
    [kcx.state :as state]))

;; --- AGENT TEMPLATES (The Brains) ---
;; Each template defines role, goal, and strict output rules to prevent "role confusion"

(def agent-templates
  {:controller
   {:role "Mission Controller"
    :goal "Manage session context and route requests to specialists"
    :template
    "ROLE: Mission Controller.
GOAL: Manage the session context and route requests to the correct specialist.
PROTOCOL:
1. **STARTUP:** If the user mentions a project name (e.g. ':proj Zodiac'), use 'switch_project'.
   - Note: This tool AUTOMATICALLY creates the project if it doesn't exist. You do not need to check first.
2. **ROUTING:** Once a project is active, route requests to :architect or :worker.
3. **LISTING:** Use ':list' to see available projects.
4. **DISCUSSION:** Answer conceptual questions directly.
TOOL USE: Use 'switch_project' for project management. Use 'handoff' tool to switch agents."}

   :curator
   {:role "Context Curator"
    :goal "Maintain the 'kcx_state.edn' file as the Single Source of Truth"
    :template
    "ROLE: Context Curator.
GOAL: Maintain the 'kcx_state.edn' file as the Single Source of Truth.
PROTOCOL:
1. Analyze what just happened in the conversation.
2. UPDATE the :active_context (task status, current files).
3. APPEND to :memory (decisions made, lessons learned).
4. PRUNE completed tasks or irrelevant context to save space.
TOOL USE: You MUST use 'update_state'. This is the final step of the workflow."}

   :architect
   {:role "System Architect"
    :goal "High-level design and planning. Do NOT write implementation code"
    :template
    "ROLE: System Architect.
GOAL: High-level design and planning. Do NOT write implementation code.
PROTOCOL:
1. Analyze the requirements.
2. Create a plan/spec (Markdown or text).
3. Identify necessary files and data structures.
4. Handoff to :worker to execute the plan.
TOOL USE: Use 'write_file' for design docs. Use 'handoff' to send to :worker."}

   :tester
   {:role "QA Engineer (Test Driven Development)"
    :goal "Ensure code quality via rigorous testing"
    :template
    "ROLE: QA Engineer (Test Driven Development).
GOAL: Ensure code quality via rigorous testing.
PROTOCOL:
1. PRE-CODE: Write failing tests that define the expected behavior.
2. VERIFY: Run tests using 'run_shell'.
3. LOOP: If tests fail, handoff to :worker with error logs.
4. SUCCESS: If tests pass, handoff to :reviewer.
TOOL USE: 'write_file' (tests), 'run_shell' (cargo test/pytest), 'handoff'."}

   :worker
   {:role "Senior Developer"
    :goal "Implement logic to satisfy requirements or fix tests"
    :template
    "ROLE: Senior Developer.
GOAL: Implement logic to satisfy requirements or fix tests.
PROTOCOL:
1. READ: Understand existing code via 'read_file' or 'list_files'.
2. IMPLEMENT: Write efficient, clean code.
3. CHECK: If in a TDD loop, handoff back to :tester.
4. SUBMIT: If finished, handoff to :reviewer.
TOOL USE: 'read_file', 'write_file', 'run_shell' (syntax check), 'handoff'."}

   :reviewer
   {:role "Lead Code Reviewer"
    :goal "Enforce standards, security, and correctness"
    :template
    "ROLE: Lead Code Reviewer.
GOAL: Enforce standards, security, and correctness.
PROTOCOL:
1. AUDIT: Read the code changes generated by the Worker.
2. CRITIQUE: Look for bugs, security flaws, or lazy shortcuts.
3. REJECT: If issues found, handoff back to :worker with a list of fixes.
4. APPROVE: If solid, handoff to :curator to close the task.
TOOL USE: 'read_file', 'handoff'."}})

;; --- DSL VERB TO AGENT ROUTING ---
;; Maps command verbs to the most appropriate agent

(def verb-routing
  {;; Direct Mapping
   "plan"     :architect
   "arch"     :architect
   "test"     :tester
   "tdd"      :tester
   "gen"      :worker
   "code"     :worker
   "fix"      :worker
   "review"   :reviewer
   "clean"    :curator
   "save"     :curator})

;; --- ROUTING FUNCTIONS ---

(defn route-intent
  "Route a DSL verb to the appropriate agent"
  [verb]
  (get verb-routing verb :controller)) ; Default to controller for unknown verbs

(defn get-agent-template
  "Get the template for a specific agent"
  [agent-key]
  (get-in agent-templates [agent-key :template]))

(defn get-agent-role
  "Get the role description for a specific agent"
  [agent-key]
  (get-in agent-templates [agent-key :role]))

;; --- HANDOFF SYSTEM ---

(defn create-handoff-message
  "Create the special handoff message that forces agent switching"
  [target-role]
  (let [template (get-agent-template target-role)]
    (str "[SYSTEM]: AGENT SWITCHING. NEW ACTIVE AGENT: " (str/upper-case (name target-role)) ".\n"
         template)))

;; --- PROMPT COMPILER ---
;; Builds rich, contextual prompts that combine project state + agent role + user intent

(defn compile-agent-prompt
  "Compile a complete agent prompt with context, role, and task"
  [verb target constraints project-state]
  (let [agent-key (route-intent verb)
        template (get-agent-template agent-key)
        agent-role (get-agent-role agent-key)]

    (str "=== KC-X AGENT EXECUTION CONTEXT ===\n\n"

         "--- 1. PROJECT MEMORY (GLOBAL CONTEXT) ---\n"
         (with-out-str (pprint/pprint project-state)) "\n\n"

         "--- 2. ACTIVE AGENT: " (str/upper-case (name agent-key)) " ---\n"
         template "\n\n"

         "--- 3. CURRENT TASK SPECIFICATION ---\n"
         "VERB: " verb "\n"
         "TARGET: " (or target "global_context") "\n"
         "INCLUDES: " (str constraints) "\n"
         "AGENT ROLE: " agent-role "\n\n"

         "--- 4. EXECUTION MANDATE ---\n"
         "Execute this task according to your role constraints.\n"
         "You MUST use the appropriate MCP tools as specified in your template.\n"
         "Do NOT provide generic responses - take concrete action.\n\n"

         "=== BEGIN EXECUTION ===")))

(defn compile-contextual-prompt
  "Compile prompt from parsed DSL command"
  [{:keys [verb target includes excludes] :as cmd}]
  (let [project-state (state/load-state)
        constraints {:includes includes :excludes excludes}]
    (compile-agent-prompt verb target constraints project-state)))

;; --- AGENT COORDINATION ---

(defn requires-handoff?
  "Determine if task requires coordination between agents"
  [verb]
  (contains? #{"gen" "create" "build" "refactor" "edit"} verb))

(defn get-workflow-sequence
  "Get the sequence of agents for complex workflows"
  [verb]
  (case verb
    ("gen" "create" "build")
    [:architect :worker :reviewer :curator]

    ("refactor" "edit")
    [:worker :reviewer :curator]

    ("fix")
    [:worker :reviewer]

    ("test" "tdd")
    [:tester :worker :reviewer :curator]

    ;; Single agent tasks
    [(route-intent verb)]))

(defn create-handoff-prompt
  "Create prompt for agent handoffs in workflows"
  [from-agent to-agent task-context previous-output]
  (let [to-template (get-agent-template to-agent)]
    (str "=== KC-X AGENT HANDOFF ===\n\n"

         "PREVIOUS AGENT: " (str/upper-case (name from-agent)) "\n"
         "CURRENT AGENT: " (str/upper-case (name to-agent)) "\n\n"

         "--- TASK CONTEXT ---\n"
         task-context "\n\n"

         "--- PREVIOUS AGENT OUTPUT ---\n"
         previous-output "\n\n"

         "--- YOUR ROLE & CONSTRAINTS ---\n"
         to-template "\n\n"

         "Continue the workflow according to your role.")))

;; --- VALIDATION ---

(defn validate-agent-output
  "Validate that agent followed their constraints"
  [agent-key output]
  (case agent-key
    :worker
    (or (str/includes? output "write_file")
        {:error "Worker agent must use write_file tool"})

    :architect
    (or (str/includes? output "write_file")
        (str/includes? output "handoff")
        {:error "Architect agent must use write_file for docs or handoff tool"})

    :curator
    (or (str/includes? output "update_state")
        {:error "Curator agent must use update_state tool"})

    :reviewer
    (or (str/includes? output "handoff")
        {:error "Reviewer must use handoff tool to continue workflow"})

    :tester
    (or (str/includes? output "write_file")
        (str/includes? output "run_shell")
        (str/includes? output "handoff")
        {:error "Tester must use write_file, run_shell, or handoff tools"})

    ;; Controller can use handoff or chat
    :controller true

    ;; Default validation passes
    true))

;; --- DEBUGGING & INTROSPECTION ---

(defn get-agent-info
  "Get detailed information about an agent"
  [agent-key]
  (get agent-templates agent-key))

(defn list-agents
  "List all available agents and their roles"
  []
  (into {} (map (fn [[k v]] [k (:role v)]) agent-templates)))

(defn explain-routing
  "Explain which agent handles which verbs"
  []
  verb-routing)